mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.config.domain.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto
    banner: "off"

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

dactiv:
  idempotent:
    ignore-classes: org.springframework.security.core.context.SecurityContext
  authentication:
    audit:
      type: elasticsearch
    plugin:
      base-packages: com.github.dactiv.basic.config.controller
      generate-sources:
        - "CONSOLE"
        - "ALL"
        - "SYSTEM"
      parent:
        config:
          name: '配置管理'
          icon: 'icon-un-config-o'
          sources: "CONSOLE"
    permit-uri-ant-matchers:
      - "/findDataDictionaries/**"
      - "/getServiceEnumerate/**"
      - "/findAccessCrypto/**"
      - "/getPublicToken/**"
      - "/getAccessToken/**"
      - "/actuator/**"
  enumerate:
    base-packages:
      - com.github.dactiv.framework.commons.enumerate
      - com.github.dactiv.framework.spring.security.enumerate
      - com.github.dactiv.basic.commons.enumeration