mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.config.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

dactiv:
  authentication:
    audit:
      type: elasticsearch
    plugin:
      base-packages: com.github.dactiv.basic.config.controller
      parent:
        config:
          name: '配置管理'
          icon: 'icon-un-config-o'
    permit-uri-ant-matchers:
      - "/findDataDictionaries/**"
      - "/getServiceEnumerate/**"
      - "/findAccessCrypto/**"
      - "/getPublicToken/**"
      - "/getAccessToken/**"
      - "/actuator/**"
  enumerate:
    base-packages:
      - com.github.dactiv.framework.commons.enumerate
      - com.github.dactiv.framework.spring.security