mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.config.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

enumerate:
  base-packages:
    - com.github.dactiv.framework.commons.enumerate
    - com.github.dactiv.framework.spring.security

plugin:
  base-packages: com.github.dactiv.basic.config.controller
  parent:
    config:
      name: '配置管理'
      icon: 'icon-un-config-o'

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

authentication:
  audit:
    type: elasticsearch
  permit-uri-ant-matchers:
    - "/findDataDictionaries/**"
    - "/findAccessCrypto/**"
    - "/getPublicToken/**"
    - "/getAccessToken/**"