mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.config.dao.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

enumerate:
  base-packages:
    - com.github.dactiv.framework.commons.enumerate
    - com.github.dactiv.framework.spring.security

plugin:
  base-packages: com.github.dactiv.basic.config.controller
  parent:
    config:
      name: '配置管理'

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@