mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.authentication.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

dactiv:
  idempotent:
    ignore-classes: org.springframework.security.core.context.SecurityContext
  authentication:
    audit:
      type: elasticsearch
    plugin:
      base-packages: com.github.dactiv.basic.authentication.controller
      parent:
        system:
          name: '系统管理'
          icon: 'icon-setting'
    permit-uri-ant-matchers:
      - "/prepare/**"
      - "/login/**"
      - "/logout/**"
      - "/actuator/**"
