mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.authentication.domain.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto
    banner: "off"

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

dactiv:
  idempotent:
    ignore-classes: org.springframework.security.core.context.SecurityContext
  authentication:
    audit:
      type: elasticsearch
    plugin:
      base-packages: com.github.dactiv.basic.authentication.controller
      generate-sources:
        - "Console"
        - "All"
        - "System"
      parent:
        system:
          name: "系统管理"
          icon: "icon-setting"
          sources: "Console"
    permit-uri-ant-matchers:
      - "/prepare/**"
      - "/login/**"
      - "/logout/**"
      - "/actuator/**"

