mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.authentication.dao.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

plugin:
  base-packages: com.github.dactiv.basic.authentication.controller
  parent:
    system:
      name: '系统管理'

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@