mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fuyu.basic.authentication.dao.entity


plugin:
  base-packages: com.fuyu.basic.authentication.controller
  parent:
    system:
      name: '系统管理'

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@