info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

authentication:
  audit:
    type: elasticsearch
  plugin:
    base-packages: com.github.dactiv.basic.file.manager.controller
  permit-uri-ant-matchers:
    - "/actuator/**"