info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@

authentication:
  audit:
    type: elasticsearch
  plugin:
    base-packages: com.github.dactiv.basic.file.manager.controller
    parent:
      file-manager:
        name: '文件管理'
        icon: 'icon-file'
  permit-uri-ant-matchers:
    - "/actuator/**"