mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.message.domain.entity
  configuration:
    call-setters-on-nulls: on
    default-enum-type-handler: com.github.dactiv.framework.mybatis.handler.NameValueEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
    banner: "off"

dactiv:
  idempotent:
    ignore-classes: org.springframework.security.core.context.SecurityContext
  authentication:
    plugin:
      base-packages: com.github.dactiv.basic.message.controller
      generate-sources:
        - "CONSOLE"
        - "ALL"
        - "SYSTEM"
      parent:
        message:
          name: '消息管理'
          icon: 'icon-message'
          sources: "CONSOLE"
    audit:
      type: elasticsearch
    permit-uri-ant-matchers:
      - "/actuator/**"
  enumerate:
    base-packages: com.github.dactiv.basic.message.enumerate

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@