mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.message.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

enumerate:
  base-packages: com.github.dactiv.basic.message.enumerate

authentication:
  plugin:
    base-packages: com.github.dactiv.basic.message.controller
    parent:
      message:
        name: '消息管理'
        icon: 'icon-message'
  audit:
    type: elasticsearch
  permit-uri-ant-matchers:
    - "/actuator/**"

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@