mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.message.dao.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto


plugin:
  base-packages: com.github.dactiv.basic.message.controller
  parent:
    message:
      name: '消息管理'
      icon: 'icon-message'

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@