mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.message.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto

dactiv:
  idempotent:
    ignore-classes: org.springframework.security.core.context.SecurityContext
  authentication:
    plugin:
      base-packages: com.github.dactiv.basic.message.controller
      generate-sources:
        - "Console"
        - "All"
        - "System"
      parent:
        message:
          name: '消息管理'
          icon: 'icon-message'
          sources: "Console"
    audit:
      type: elasticsearch
    permit-uri-ant-matchers:
      - "/actuator/**"
  enumerate:
    base-packages: com.github.dactiv.basic.message.enumerate

info:
  version: @version@
  name: @name@
  artifact-id: ${spring.application.name}
  group-id: @groupId@