server:
  servlet:
    encoding:
      force: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  aop:
    proxyTargetClass: true
  jackson:
    default-property-inclusion: non_empty
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true

dactiv:
  authentication:
    users:
      - data:
        - name: "feign"
          password: "feign"
          roles: "BASIC"
        cache:
          name: "spring:security:default:users:feign"