server:
  servlet:
    encoding:
      force: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  aop:
    proxyTargetClass: true
  jackson:
    default-property-inclusion: non_empty
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true

dactiv:
  authentication:
    users:
      - name: "feign"
        password: "feign"
        roles: "BASIC"