server:
  servlet:
    encoding:
      force: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  aop:
    proxyTargetClass: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    encoding:
      force: true
  security:
    user:
      name: feign
      password: feign
      roles: BASIC
  elasticsearch:
    rest:
      uris: http://localhost:9200