spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authentication?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: 用户名
    password: 密码
    publisher-returns: true
    publisher-confirm-type: correlated
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        retry:
          initial-interval: 45000
          max-interval: 80000
          enabled: true
    cache:
      channel:
        size: 100