spring:
  datasource:
    url: jdbc:mysql://localhost:3306/config?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
  application:
    crypto:
      access:
        algorithm-mode:
          algorithm: "AES"
          mode: "CBC"
          block-size: 0
          padding-scheme: "PKCS5"
          streaming-mode: "CBC"
          streaming-block-size: 0
          streaming-padding-scheme: "PKCS5"
          keySize: 128
          initialization-vector-size: 128
        rsa:
          private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdMDFu58k7UIXIfPP4Oh1Q3YrR1tzT7LKf+DyULZz6HmKYinYyH13yVMPM7Su8fOG/UjZqLM0Z8jeSrTRTjURBDL+/ULZUeAE30VD/1BMv/6hZD5KhlnlplkSV4dgi2BGVza/keizy1wgWr7YvgYaZYtDmc5vnYITQYK5nrBydWSqvBAYUqPq7CnNbtVZ1j8KG832KhfL8tKSJ4ToHlTy+FTF5x1GcRdY5EPlLUi4CJwlC33fqJJPh9oveo9hGMyWt4jG7DirCNTkqklj7tm1GQndMm30ad9CR6iHRFFSXFOJ0hpIPYK4Fyby4ymn+sGdMMgM2OgtBNx2NZfXJLQrZAgMBAAECggEAQ3T0MfE81bynvTOKi8N840BAG++Gk1goDCi+7qRokppJm8cIFFiLu7yOzroVo+1AABgrDAOv/WuKV+MG6rhcS0JKY7MinDtn4mlsxm1f0qB3wcjCF6B4+EwpoNzsIX/yhARicL3R3mFTslCz8c03U0op9kw04uXz+W0US598JDX8iVWKp1Mm3KL+YMV/95esOQKvyoCBRWyS4QvmEjXrPGy3D1dQ8HcMSVt4WKlTTXTwpaZcXkKuYAozxrj7bWRlLlgHhJ6XBF6qGJGzHjurZcfU+2nPt8V531q+X+u9+t+L1fEAugrrHwLKrhDJul7OVUPumI23HBzxaWi4mX/QkQKBgQDTKCIHz4kg6AaDjZvFsfrHI19rcXicTME0z9VWqH5QYAygwC3wAQqPD3Cla4wAlhrSg37hzkukUdfqEh6UsskoFBNi21A3vpljbbwDw2IZSrc4bMOIzj5vn3HwqSSnL7yTaPnxceN45iIsywJxwcrWRuI/5CSTxxbQFg42mzOLbQKBgQC+kfpJhPEeTV5nUcO+NeZpgrMhGLsXz086xgI/ctLAsRUj46OOFPJTcBRm4Nw7gVOVXBu+/9k4pbId9DMIexXc2CNQe9XDlTFMWw3N/38/luqxlA9zCCNDd3KGF4YcVgJw6PixJ0zKkty2gV6RXPWB1mxyAY28yG6fWLi/xOwNnQKBgEGkBzgwXuuY1XWNzu/dDR1ctKv84UaNYb5eIW7IAERSJ3rNYzppyHOClD0IOsRv5TSt5gKiE8eoHZvJODJ3hars2r3veXdqy9op4bm1wkgkfuKOhRaBLs2aXlw26IsEfvXAO3rAMbuCpvsPvNnKKZkE/g5oiKpbyI61XIPDKXndAoGAA/sWqFx/kOt60lux5BJKKuARD9rtZZTuCcNDHsIuRtosH+DMdNZZLYcE1hVSZGfSMCeJaNb9WaKUcu279yxjC4b0TeUYVQqTyg2I30m8Bb8ITgdSv0tnOSyQlt587bCaQnOLZl/0ybKBq8pOCGlRs5GgGE2SAWSKcweubEsXxz0CgYEAouZnNfoCnlsQiJs/029jMkoObKn6KAFoArXFFm+tRVmautejbELNlrDQ+tWGHNnZvGkWvZTauqvEd7jL+lYPD9pa5N0hD3QS8w1ESrZJhFnwoqadQKhnB4m7P+2jA8im/rIs3H64gXdn8OJBFtDYsg/HKEbD6e4KXrdVMOtDTUw=
          public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnTAxbufJO1CFyHzz+DodUN2K0dbc0+yyn/g8lC2c+h5imIp2Mh9d8lTDzO0rvHzhv1I2aizNGfI3kq00U41EQQy/v1C2VHgBN9FQ/9QTL/+oWQ+SoZZ5aZZEleHYItgRlc2v5Hos8tcIFq+2L4GGmWLQ5nOb52CE0GCuZ6wcnVkqrwQGFKj6uwpzW7VWdY/ChvN9ioXy/LSkieE6B5U8vhUxecdRnEXWORD5S1IuAicJQt936iST4faL3qPYRjMlreIxuw4qwjU5KpJY+7ZtRkJ3TJt9GnfQkeoh0RRUlxTidIaSD2CuBcm8uMpp/rBnTDIDNjoLQTcdjWX1yS0K2QIDAQAB