spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    sentinel:
      transport:
        port: 8787
        dashboard: localhost:8787
      eager: true
      datasource:
        gateway-api-group:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            data-id: sentinel-gateway-api-group.json
            rule-type: GW_API_GROUP
    gateway:
      routes:
        # 配置 socketio 路由
        - id: socket
          predicates:
            - Path=/socket.io/**
          uri: lb://netty-socket-server
      discovery:
        locator:
          enabled: true
          predicates:
            - name: Path
              args:
                pattern: "'/'+serviceId+'/**'"
          filters:
            - name: PreserveHostHeader
            - name: RewritePath
              args:
                regexp: "'/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
            - name: AddRequestHeader
              args:
                name: "'X-REQUEST-CLIENT'"
                value: "'SPRING_GATEWAY'"

dactiv:
  gateway:
    algorithm:
      name: "AES"
      mode: "CBC"
      block-size: 0
      padding-scheme: "PKCS5"
      streaming-mode: "CBC"
      streaming-block-size: 0
      streaming-padding-scheme: "PKCS5"
      keySize: 128
      initialization-vector-size: 128