dactiv:
  minio:
    endpoint: 终端地址
    access-key: 访问密钥
    secret-key: 私有密钥
    auto-delete:
      expiration:
        - bucket-name: "message.attachment.email"
          expiration-time:
            value: 30
            unity: DAYS
        - bucket-name: "message.attachment.site"
          expiration-time:
            value: 30
            unity: DAYS
  message:
    sms:
      channel: yimei
      yimei:
        id: appid
        password: 密码
        url: 接口地址
    site:
      channel: umeng
      umeng:
        url: 接口地址
        production-mode: false
        expire-time:
          value: 7
          unit: Days
        ios:
          app-key: app 密钥
          secret-key: 安全密钥
        android:
          app-key: app 密钥
          secret-key: 安全密钥
          push: true
          activity: 路径
    mail:
      accounts:
        marketing:
          username: 发送营销邮箱用户名
          password: 发送营销邮箱密码
        notice:
          username: 发送通知邮箱用户名
          password: 发送通知邮箱密码
        warning:
          username: 发送预警邮箱用户名
          password: 发送预警邮箱密码
        system:
          username: 发送系统邮箱用户名
          password: 发送系统邮箱密码
      host: smtp.exmail.qq.com
      protocol: smtp
      port: 465
      properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true
              socketFactory:
                class: com.sun.mail.util.MailSSLSocketFactory
                fallback: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: 用户名
    password: 密码
    # 开启发送失败返回
    publisher-returns: true
    # 开启发送确认
    publisher-confirm-type: correlated
    listener:
      # 开启 ack
      simple:
        acknowledge-mode: manual
        concurrency: 8
        retry:
          # 重试初始间隔时间
          initial-interval: 2000
          # 间隔时间乘子，间隔时间 * 乘子 = 下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
          # 启用重试
          enabled: true
      # 开启 ack
      direct:
        acknowledge-mode: manual
        retry:
          # 重试初始间隔时间
          initial-interval: 2000
          # 间隔时间乘子，间隔时间 * 乘子 = 下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
          # 启用重试
          enabled: true
    # 支持消息的确认与返回
    template:
      mandatory: true