dactiv:
  minio:
    endpoint: 终端地址
    access-key: 访问密钥
    secret-key: 安全密钥
  authentication:
    device-id:
      overwrite-session: false
      cache:
        name: "socket:server:spring:security:context:"
        expires-time:
          value: 7
          unit: DAYS
  socket:
    client:
      enable: false
    server:
      port: 8800
      valid-token-url: http://localhost:8080/authentication/validMobileUserDetails

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socket_server?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 用户名
    password: 密码
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: 用户名
    password: 密码
    # 开启发送失败返回
    publisher-returns: true
    # 开启发送确认
    publisher-confirm-type: correlated
    listener:
      # 开启 ack
      simple:
        acknowledge-mode: manual
        concurrency: 8
        retry:
          # 重试初始间隔时间
          initial-interval: 2000
          # 间隔时间乘子，间隔时间 * 乘子 = 下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
          # 启用重试
          enabled: true
      # 开启 ack
      direct:
        acknowledge-mode: manual
        retry:
          # 重试初始间隔时间
          initial-interval: 2000
          # 间隔时间乘子，间隔时间 * 乘子 = 下一次的间隔时间，最大不能超过设置的最大间隔时间
          multiplier: 2
          # 启用重试
          enabled: true
    # 支持消息的确认与返回
    template:
      mandatory: true