info:
  version: @version@
  name: @name@
  artifact-id: @artifactId@
  group-id: @groupId@

dactiv:
  authentication:
    permit-uri-ant-matchers:
      - "/health/**"
      - "/joinRoom/**"
      - "/broadcast/**"
      - "/multipleUnicast/**"
      - "/unicast/**"

