info:
  version: @version@
  name: @name@
  artifact-id: @artifactId@
  group-id: @groupId@

mybatis-plus:
  type-aliases-package: com.github.dactiv.basic.socket.server.entity
  configuration:
    call-setters-on-nulls: on
  global-config:
    db-config:
      id-type: auto
    banner: "off"

dactiv:
  spring:
    web:
      mvc:
        base-packages: com.github.dactiv.basic.socket.server
  authentication:
    plugin:
      base-packages: com.github.dactiv.basic.socket.server.controller
      generate-sources:
        - "SocketUser"
        - "All"
        - "System"
      parent:
        socket-server:
          name: "socket 服务管理"
          icon: "icon-plug-socket"
          sources: "SocketUser"
    permit-uri-ant-matchers:
      - "/health/**"
      - "/joinRoom/**"
      - "/broadcast/**"
      - "/multipleUnicast/**"
      - "/unicast/**"
      - "/actuator/**"
  enumerate:
    base-packages: com.github.dactiv.basic.socket.server.enumerate
